# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import DunkCityDynasty.env.multi_machine.machine_comm_pb2 as machine__comm__pb2


class ClientCommStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Cmd = channel.unary_unary(
                '/comm.ClientComm/Cmd',
                request_serializer=machine__comm__pb2.ClientCmd.SerializeToString,
                response_deserializer=machine__comm__pb2.Reply.FromString,
                )


class ClientCommServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Cmd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientCommServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Cmd': grpc.unary_unary_rpc_method_handler(
                    servicer.Cmd,
                    request_deserializer=machine__comm__pb2.ClientCmd.FromString,
                    response_serializer=machine__comm__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comm.ClientComm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientComm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Cmd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comm.ClientComm/Cmd',
            machine__comm__pb2.ClientCmd.SerializeToString,
            machine__comm__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
